<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FastDB.NET_Browser</RootNamespace>
    <AssemblyName>FastDB.NET_Browser</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>Database-01.ico</ApplicationIcon>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastDB.NET\FastDB.NET.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Database-01.ico" />
    <Content Include="iconfinder_Database_2_40095.ico" />
  </ItemGroup>
</Project>
