<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>FastDB.NET_Test</RootNamespace>
    <AssemblyName>FastDB.NET_Test</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastDB.NET\FastDB.NET.csproj" />
  </ItemGroup>
</Project>
